version: '2'

services:
  grafana:
    image: grafana/grafana
    restart: always
    expose:
        - "3000"
    ports:
        - 3000:3000
    external_links:
      - prometheus
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel, grafana-simple-json-datasource