version: '2'

services:
    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
        - prometheus_data:/promtheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
        ports:
            - 9090:9090
        restart: always
        
volumes:
    prometheus_data: