version: '3.7'

services:
    prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/promtheus
    command:
     - '--config.file=/etc/prometheus/prometheus.yml'
    expose:
      - "9090"
    restart: always

    node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    expose:
      - "9100"
    restart: always

    grafana:
      image: grafana/grafana
      restart: always
      expose:
        - "3000"
      external_links:
        - prometheus
      environment:
        GF_INSTALL_PLUGINS: grafana-clock-panel, grafana-simple-json-datasource
        LETSENCRYPT_HOST: grafana.lab20.cpsudevops.com 
        networks: 
            - monitoring
